baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Kross | Hugo Portfolio Template"
[[menu.main]]
URL = "portfolio"
name = "IPFS MEDIA"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "Floating in the ether of Web3"
author = "“Give me Web3 or give me Death” - Mike"
copyright = "https://ipfs.infura.io/ipfs/QmYPTbT6Q1aVCsekE8ZzfjJu9h9gjd4oTswHLJ6JBAyfku"
description = "Thank you for your time"
email = "mikenewton.eth"
google_analitycs_id = "Your ID"
home = "Home"
logo = "/images/configuration-params-logo.png"
phone = "1 (714) 777 3456"
social = []
theme_color = "#a82011"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
